### ISSUE TITLE
项目报错Unable to find a matching configuration of project 

### ISSUE THREAD

**Issue by devzld** [luojilab/DDComponentForAndroid#108]
独立运行组件时，项目报这个错是什么原因

Unable to find a matching configuration of project :chat:
  - Configuration 'debugApiElements':
      - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
      - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
      - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Apk'.
      - Required org.gradle.usage 'java-runtime' and found incompatible value 'java-api'.
  - Configuration 'debugBundleElements':
      - Required com.android.build.api.attributes.BuildTypeAttr 'debug' but no value provided.
      - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
      - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but no value provided.
      - Required org.gradle.usage 'java-runtime' and found incompatible value 'android-bundle'.
  - Configuration 'debugMetadataElements':
      - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
      - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
      - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Metadata'.
      - Required org.gradle.usage 'java-runtime' but no value provided.
  - Configuration 'debugRuntimeElements':
      - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
      - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
      - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Apk'.
      - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.

**Comment by miaoyongjun** [comment]
你的解决方案是什么

**Comment by miaoyongjun** [comment]
@devzld

**Comment by devzld** [comment]
是我配置错了，主module的配置文件gradle.perties @miaoyongjun

**Comment by miaoyongjun** [comment]
能贴下你的主module配置以及独立组件的配置吗  我看看哪里和我这边不一样 @devzld   感谢

**Comment by miaoyongjun** [comment]
已解决

**Comment by 790396054** [comment]
@devzld  @miaoyongjun 我也遇到了，请问如何解决？

**Comment by miaoyongjun** [comment]
独立项目运行的时候  吧app的gradle配置注释下

**Comment by 790396054** [comment]
@miaoyongjun  好的，多谢

**Comment by zgq105** [comment]
@moyokoo 正解

**Comment by chenlulujing** [comment]
这个怎么解决？

**Comment by woodgreat** [comment]
> 是我配置错了，主module的配置文件gradle.perties @miaoyongjun

请问配置怎么错了,您倒是说明白呀,我们现在也碰到这个问题卡半个月了,T T

**Comment by woodgreat** [comment]
> 独立项目运行的时候 吧app的gradle配置注释下

请问如何配置,急呀,谢谢
------------------------------------
pping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Parsing E:\Android\android-sdk\system-images\android-28\google_apis_playstore\x86\package.xml
Parsing E:\Android\android-sdk\system-images\android-28\google_apis_playstore\x86_64\package.xml
Parsing E:\Android\android-sdk\tools\package.xml
Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
SDK initialized in 16958 ms
Using incremental javac compilation for :pigappt debug.
Using incremental javac compilation for :pigappt debugUnitTest.
Using incremental javac compilation for :pigappt release.
Using incremental javac compilation for :pigappt releaseUnitTest.
Using incremental javac compilation for :pigappt debugAndroidTest.
All projects evaluated.
Selected primary task 'assembleRelease' from project :

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':pigappt:compileReleaseJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':pigappt:releaseCompileClasspath'.
   > Could not resolve project :libcocos2dx.
     Required by:
         project :pigappt
      > Unable to find a matching configuration of project :libcocos2dx: None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 33s
VCS Checkout Cache (G:\c\build\jsb-link\frameworks\runtime-src\proj.android-studio\.gradle\vcs-1) removing files not accessed on or after Thu Dec 02 09:25:05 CST 2021.
VCS Checkout Cache (G:\c\build\jsb-link\frameworks\runtime-src\proj.android-studio\.gradle\vcs-1) cleaned up in 0.005 secs.
执行命令出错，返回值：1。
