### ISSUE TITLE
组件化数据传递问题

### ISSUE THREAD

**Issue by wt959790** [luojilab/DDComponentForAndroid#11]
有些组件的入口 activity 需要从其他组件传值过来的怎么办，要写模拟数据吗？

**Comment by gejiashu** [comment]
UIRouter openUri 方法的bundle参数可以传递的吧

**Comment by wt959790** [comment]
单独运行的时候

**Comment by mqzhangw** [comment]
是的，使用bundle可以传递数据。
如果是单独运行，需要在runalone中的增加模拟数据的设置逻辑

**Comment by jianjin33** [comment]
公共资源basicres模块是否应该在最底层？因为basiclib可能会用到res文件

**Comment by leobert-lan** [comment]
当前本人正在处理路由和传值部分的内容，按照我的计划是先实现注解实现路由定义，自动化解析bundle数据，然后实现URI的query部分取值，目标是：使用runalone进行局部测试的时候，也可以使用配置的一系列的URI，通过注解或者其他形式注入，进行测试，而不用进行代码侵入。

**Comment by mqzhangw** [comment]
新的UI跳转功能已经完成，请参考最新代码
