### ISSUE TITLE
第一次运行app的无法卸载Share组件,需要点击一次安装 再点击一次卸载才可以.

### ISSUE THREAD

**Issue by gejiashu** [luojilab/DDComponentForAndroid#12]
看了博客写的非常好,非常赞,我以前也经常看逻辑思维,只不过今年不在优酷播了之后就没看过了 哈哈哈.

发现了一个bug 第一次点击是无法卸载组件的.调试了一下应该是通过字节码插入模式调用IApplicationLike.onCreate的时候没有注册到Router的Map里面,导致我点击了卸载Share组件之后还能点击下面的文字跳转到ShareAct.不知道能否在用gradle插件 进行字节码插入的的时候把组件也注册到Router里面,这样的话应该就没有这个问题了.

**Comment by mqzhangw** [comment]
这个的确是一个bug，已经修复，谢谢反馈~~
看罗辑思维欢迎下载得到app客户端，里面有更多精彩的内容~~
