### ISSUE TITLE
mvp架构的话，涉及到2个模块存在公共的操作的话，这样的话公共操作就得提取放到那个service里了吧

### ISSUE THREAD

**Issue by Anayuta** [luojilab/DDComponentForAndroid#20]

**Comment by mqzhangw** [comment]
mvp应该是在每个组件内部做的架构吧，不清楚为啥需要两个组件之间交互。
组件之间公共操作需要放到service中。

**Comment by Anayuta** [comment]
就是假如A lib存在点赞功能，B lib也存在点赞功能，这样的话应该得把这个功能抽取出来作为父类使用吧

**Comment by ViTess** [comment]
mvp应该是针对app内的架构，组件化是针对整个工程而言。
如果按你说的，应该是点赞功能抽出来做模块，注册接口到service里，给A模块和B模块调用

**Comment by Anayuta** [comment]
哦，这样也可以，谢谢了。
