### ISSUE TITLE
首页入口为fragment的情况如何组件化

### ISSUE THREAD

**Issue by Aeiric** [luojilab/DDComponentForAndroid#24]
如题，比如业务分为home、a、b、c,但是home、a、b、c在主工程对应4个模块的宿主fragment，这种情况有什么好的建议吗

**Comment by mqzhangw** [comment]
demo中readercomponent的入口就是fragment，可以通过接口的形式向其他组件提供这个fragment。
如果组件需要单独运行，则需要创建一个测试用的host activity。

**Comment by Aeiric** [comment]
谢谢解答，这个问题我已经搞清楚了，其实组件化来说，如果需要使用组件内某个fragment。比如业务组件A要使用业务组件B的fragment，可能A内部仅仅只是个viewpager容器需要复用B里面的。那么在A里面直接用Router拿到B里面的fragment实例就可以。
组件化思想禁忌是引入组件里面的相关类，这个重点把握好就ok了～

**Comment by mqzhangw** [comment]
赞，理解的很到位
