### ISSUE TITLE
可以麻烦录制一份视频教程吗

### ISSUE THREAD

**Issue by edifangyi** [luojilab/DDComponentForAndroid#25]
如题：小白

**Comment by JackiePenghe** [comment]
我也是，感觉看不太懂

**Comment by mwj1103** [comment]
同求

**Comment by xiangyao0906** [comment]
同求

**Comment by mqzhangw** [comment]
你是对原理不清楚还是对接入不清楚呢？
录音频可能暂时没有时间

**Comment by edifangyi** [comment]
@mqzhangw ,,,接入这块，试了一天了，没成功唉

**Comment by mqzhangw** [comment]
demo运行成功了吗？要接入自己项目需要自定制，具体可以看wiki

**Comment by edifangyi** [comment]
@mqzhangw ,Demo可以运行。我接入创建的Demo除了包名不同外，都是按照给的Demo写的。现在可以运行，但是app 没有展示 readercomponent。。单独运行readercomponent，点击“欢迎每天听本书---”，没有启动分享组件。。

在 DDComponen 定制化 的修改包名，这里我也改成自己的了

**Comment by mqzhangw** [comment]
每个组件需要增加一个gradle.properties文件，里面配置debugComponent以及compileComponent属性，配置好之后sync才可以生效。如果使用字节码注入的方式，需要修改包名。如果使用反射的方式，需要在application中手动加上注册的代码。建议先使用反射的方式

**Comment by edifangyi** [comment]
把app的MyApplication 的反射注释打开是可以用了呢。
这是 组件中 写的
![image](https://user-images.githubusercontent.com/12421552/31010698-5423bbdc-a53e-11e7-924f-55005d99cc56.png)

**Comment by edifangyi** [comment]
谢谢~๑乛◡乛๑

**Comment by mqzhangw** [comment]
客气，方案细节有点多，建议仔细看一下文章
