### ISSUE TITLE
子模块单独运行很有启发。然而，子模块里维护两份AndroidManifest，随着Activity的增多会不会难以维护。

### ISSUE THREAD

**Issue by fashare2015** [luojilab/DDComponentForAndroid#26]
如题

**Comment by leobert-lan** [comment]
不会，分Component的原则是将功能相当独立的完整模块进行分离，但实际情况下，这样一个模块不会包含过多的activity，两只手差不多能数完。而且独立模块运行的目的是对独立模块进行测试，两份清单文件也不应当出现个性化的差异。

**Comment by fashare2015** [comment]
嗯嗯，应该不会有太多Activity.

**Comment by mqzhangw** [comment]
@leobert-lan 👍
