### ISSUE TITLE
comgradle插件不支持Variant

### ISSUE THREAD

**Issue by 5830327wy** [luojilab/DDComponentForAndroid#27]
期待comgradle插件在添加依赖的过程能区分Variant，期望能给予支持，谢谢！
比如app有:
2个productFlavors: uat和prod
2个buildType:debug和release
那么会有4个Variant: uatDebug、uatRelease、prodRelease、prodDebug 
看了下插件源码，是根据assemble任务是否是debug和release来添加依赖的，只区分了debug和release。

在library我尝试加入了以下代码：
project.afterEvaluate {
        project.android.libraryVariants.all { BaseVariant variant ->
.....}
}
将打包区分Variant输入到不同路径下和发布是ok的。但在application去动态添加依赖一直不成功。
比如添加:
uatDebugCompile project(path: ':component_base', configuration: 'uatDebug')
uatReleaseCompile project(path: ':component_base', configuration: 'uatRelease')
prodDebugCompile project(path: ':component_base', configuration: 'prodDebug')
prodReleaseCompile project(path: ':component_base', configuration: 'prodRelease')

在project.afterEvaluate后添加，会报不能在afterEvaluate后改动依赖的错误。
不在project.afterEvaluate后添加，又不能获取到Variant，很纠结...

**Comment by mqzhangw** [comment]
这个你可以尝试修改gradle的源码，分析task任务，识别出flavor，然后就像源码中添加组件依赖一样，添加你需要的依赖
