### ISSUE TITLE
新建项目gradle发布到本地出问题

### ISSUE THREAD

**Issue by liukai2530533** [luojilab/DDComponentForAndroid#28]
Error:(2, 0) Could not get unknown property 'mainmodulename' for root project 'ComponentPlugDemo2' of type org.gradle.api.Project.

为什么会找不到我的主项目名字 需要设置吗？

**Comment by mqzhangw** [comment]
你需要在root project目录下面的gradle.properties文件中增加mainmodulename属性，其值就是你的主项目module，一般都是“app”

**Comment by liukai2530533** [comment]
为什么我在你的工程中依赖apply plugin: 'com.dd.comgradle' 之后 如果不设置combuild和applicatonName 会报错   我自己新建的工程 不设置combuild和applicatonName 它不报错 也不会走这个方法 没有进入到runalong的测试application中？

**Comment by liukai2530533** [comment]
谢谢，解决问题了 ，我现在在主项目app中配置了
debugComponent=readcomponent
compileComponent=readcomponent
为什么不能自动的注册组件。例如：

 private void showFragment() {
        //每次启动都需要手动注册一次才能调用，大神的项目中可以直接运行
        Router.registerComponent("com.meiyue.readcomponent.applike.ReadAppLike");

        if (mFragment != null) {
            ft = getSupportFragmentManager().beginTransaction();
            ft.remove(mFragment).commit();
            mFragment = null;
        }
        Router router = Router.getInstance();
        ........

**Comment by mqzhangw** [comment]
注册组件现在有两种模式，自动注册（字节码插入）需要在配置中开启isRegisterCompoAuto=true,具体参考demo；另一种是反射注册，这个在application中注册就可以了

**Comment by liukai2530533** [comment]
谢谢，再问一个在实际开发中关于混淆的问题 是每一个组件单独混淆 还是在app主项目中设置混淆就行了？

**Comment by mqzhangw** [comment]
只需要在主项目里面设置混淆就可以了

**Comment by liukai2530533** [comment]
万分感谢，O了，暂时没问题了

**Comment by mqzhangw** [comment]
客气了，有问题随时交流，觉得好的话给个star😆
