### ISSUE TITLE
请问子组件如何调用App组件的接口？

### ISSUE THREAD

**Issue by spysoos** [luojilab/DDComponentForAndroid#29]
请问子组件如何调用App组件的接口？ 是不是也要在App里实现IApplicationLike接口？

**Comment by mqzhangw** [comment]
和调用其他组件同样的道理，app也需要在componentservice中定义自己的服务，其他组件针对service编程就可以了。唯一的区别是子组件不能依赖主项目来单独调试，必须是主项目依赖子组件来进行。如果主项目只依赖这一个组件，其实和单独编译子组件效果基本是一致的。
