### ISSUE TITLE
一些小小建议

### ISSUE THREAD

**Issue by Jusenr** [luojilab/DDComponentForAndroid#3]
1.页面跳转这块建议使用ARouter
2.关于gradle打包所有*.aar文件这块 希望可以给出详细文档

**Comment by mqzhangw** [comment]
UI跳转这块使用ARouter可能有点重，后面会开源一个适合这个方案的。
第二个问题你是说发布吗？只需要修改一下isRunalone，运行module:assembleRelease就可以生成aar并拷贝到仓库中。

**Comment by Mr9527** [comment]
请问 com.dd.comgradle 这个插件的源码我可以在哪里得到吗

**Comment by Jusenr** [comment]
https://github.com/Jusenr/DDComponentForAndroid   [build-gradle]  library.


jusenr@163.com
 
发件人： ChenZhaoJun
发送时间： 2017-09-15 09:10
收件人： luojilab/DDComponentForAndroid
抄送： Jusenr; Author
主题： Re: [luojilab/DDComponentForAndroid] 一些小小建议 (#3)
请问 com.dd.comgradle 这个插件的源码我可以在哪里得到吗

**Comment by mqzhangw** [comment]
新的UI跳转功能已经release
