### ISSUE TITLE
IApplicationLike 能有办法获取Context对象吗？

### ISSUE THREAD

**Issue by gordonpro** [luojilab/DDComponentForAndroid#30]
如果某个Component需要在使用前，初始化。而且初始化需要Context对象，有什么好的处理方式吗？

**Comment by mqzhangw** [comment]
有两个途径，一是主项目提供一个接口返回ApplicationContext，二是将BaseApplication抽离到basicres或者basiclib里面，在BaseApplication提供一个静态方法来获取ApplicationContext。

**Comment by gordonpro** [comment]
再问个问题
`reader` 这个组件在 `isRunAlone` 模式下，是如何知道要把 `share` 这个组件编译到apk的。我看没有 compile指令.

**Comment by gordonpro** [comment]
`componentlib` 和 `basiclib` 有什么区别吗？ 

basiclib 貌似这个工程没有被其他工程引用

**Comment by leobert-lan** [comment]
这个basiclib是用来演示一些基本库如何集成到项目中的，比如自定义的数据结构lib，自定义view的lib，工具类库等，将其作为底层的lib。而Componentlib封装了一个独立的组件module的抽象部分和router等关键的类。另外 a依赖b，b依赖c，都是通过compile module的方式添加依赖的话，a就没必要再显示的声明对c的依赖了。如果是AAR包的话会因为路径而出现一些问题。
