### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by zhangguobing** [luojilab/DDComponentForAndroid#33]
如果阅读与分享等组件单独调试运行的时候都需要一个公共的模块，比如Application类（用来初始化必要组件），启动页，可能还需要登录注册模块等，这部分代码放在哪比较合适。

**Comment by leobert-lan** [comment]
这个公共的模块，比如说用户登录注册模块，它是拥有界面，可以做一个单独的组件module，通过UI路由注册Activity的页面导航，通过在Component-Service module中定义接口暴露module所能够提供的业务。

关于Application，如果仅仅是获得Application类实例，那么通过Context实例就能得到。但是大家都是在Application子类中封装了一定的逻辑，而且想要的是该Application子类，在这款方案中，推荐的做法是定义接口，通过接口去访问，（接口是定义在Component-Service module中的），而接口的实现，‘app’module中的Application子类一定会做实现，其他的runalone模块，建议也做实现。  需要注意的是，以前可能你用单例去获得Application的具体子类实例，现在是通过Router得到接口的实现类实例。

**Comment by leobert-lan** [comment]
by the way，一定要注意，app module虽然是宿主，但是app module 和share module 从架构层次上是平级的，没有上下依赖关系，所以不能够抱有从一个平级的module中获取“明确知识”的想法，只能从下层的抽象的部分获取知识，而且这些知识应该是非具体的、抽象的。

**Comment by zhangguobing** [comment]
好的，大概明白了。多谢。

**Comment by mqzhangw** [comment]
@leobert-lan 👍👍，还有一个方法，也是目前得到采用的方式，就是在basicres中创建一个BaseApplication，app或者其他组件都继承这个BaseApplication，在BaseApplication中提供一个静态方法获取其中的applicationcontext，这样app或者组件都是可以直接访问的。

**Comment by leoncoding** [comment]
@leobert-lan 请问在在basicres中创建一个BaseApplication，app或者其他组件都继承这个BaseApplication，那这个子Application需要在组件的AndroidManifest里面注明吗？？

**Comment by leobert-lan** [comment]
@leoncoding 在runalone配套的manifest文件中需要指定路径。对于整个项目，在主Module的manifest中指定相应的那个就行了。

_虽然我没有尝试一下，所有的manifest都指定该Module中的Application子类路径应该也是没有问题的。应该不会影响编译时合并manifest。_
