### ISSUE TITLE
实体类问题

### ISSUE THREAD

**Issue by CLOUD-wuzichen** [luojilab/DDComponentForAndroid#36]
求问：两个module都要用到相同的bean，是copy放在各自模块？还是把所有bean统一放在一个资源module里面好些？类似问题也例如公共接口等。

**Comment by mqzhangw** [comment]
放到componentservice里面，当做组件提供的服务的一部分即可

**Comment by CLOUD-wuzichen** [comment]
大神的意思是几个模块共同用到的bean和网络请求都放在componentservice里面，那这个componentservice组件内部就比较杂了，例如：可能有钱包和保险module用到的查询用户信息接口，有可能有别的业务的接口混在一起，同时也demo中对外暴露的fragment。是这个意思吗？
