### ISSUE TITLE
求助，在使用Dagger2中遇到了麻烦

### ISSUE THREAD

**Issue by zhangguobing** [luojilab/DDComponentForAndroid#37]
我想在basiclib module中的ActivityComponent接口中注册inject某一个具体的Activity的方法，可是根本访问不到该Activity，因为该Activity在其他的module中，根本访问不到。哪位大牛有没有好的办法可以解决这个问题

**Comment by mqzhangw** [comment]
不太明白你为啥需要在basiclib里面引用组件的Activity，basiclib在框架中是底层依赖库，是不可以引用上层的类的，这种原则性还是不要打破
