### ISSUE TITLE
build-gradle:0.0.1和'./repo'为神魔不能选其一？

### ISSUE THREAD

**Issue by Jusenr** [luojilab/DDComponentForAndroid#4]
1.
dependencies {
        classpath 'com.mrzhang.andcomponent:build-gradle:0.0.1'

        // NOTE: Do not place your com.putao.login.runalone dependencies here; they belong
        // in the individual module build.gradle files
    }

2. 
maven { url uri('./repo') }

两个为何不能选择一个 ，少一个报错。

**Comment by mqzhangw** [comment]
这个你是gradle的标准用法，必须同时指定，具体可以google几篇自定义gradle插件的文章。
