### ISSUE TITLE
引用第三方库只能采用compile的方式

### ISSUE THREAD

**Issue by dayday0769** [luojilab/DDComponentForAndroid#41]
发现引用第三方库只能采用compile的方式，若用provided或者apt的方式都会导致找不到第三方的库，会报“错误：程序包xxx不存在”

**Comment by mqzhangw** [comment]
你用的库是aar的吧？

**Comment by dayday0769** [comment]
应该是，maven上的库

**Comment by mqzhangw** [comment]
那就只能compile，如果你使用gradle3.0.0，还可以使用runtimeOnly，可以参考我简书的第三篇文章

**Comment by leobert-lan** [comment]
是不是在独立运行Component Module的情况下出现的？或者说，这次运行所有参与编译的Module中没有任何一个申明了需要编译入该三方库？

**Comment by dayday0769** [comment]
所有参与编译的modele都没有声明

**Comment by leobert-lan** [comment]
均建立在gradle插件版本＜V3.0.0情况下讨论：
--------
这样的话一定会找不到的，当前的方案有一个问题就是对某个独立组件进行独立运行时，容易遗忘部分依赖的申明。
举个例子：app Module（主）和 read Module和share Model（两副组件），read-M 和share-M 使用provided声明一个依赖，app-M通过compile声明了这个依赖（这在以往的实践中很常见，有效避免了重复引入一个库带来的编译问题），**但是在对read-M进行独立运行时就很容易遗忘修改使用compile去声明这个依赖。**

看起来这个问题需要这样解决：编译plugin需要将所有参与编译的Module中以provided形式声明的依赖，在本次编译时，无遗漏的使用compile形式在主Module中声明依赖。

考虑到需要避免在主Module中同时使用provided和compile声明同一个依赖、以及gradle插件3.0.0以下和以上的完整兼容性测试，it's a real challenge and much more time need to pay to solve this defect.
--------
**相对折中一点的处理方式是在baselib中使用compile的形式申明该依赖**。

**Comment by dayday0769** [comment]
嗯，我目前暂时就是在baselib中使用compile的形式进行依赖来处理这个问题

**Comment by mqzhangw** [comment]
目前得到得第三方库也都是交给basiclib引入，除非组件需要一个特殊的库，才交给这个组件自己通过compile引入。
