### ISSUE TITLE
请问如何引入maven仓库的aar

### ISSUE THREAD

**Issue by HuRuWo** [luojilab/DDComponentForAndroid#42]
我想引入发布到maven的aar文件，但是失败了。

![QQ截图20171110100644.png](http://upload-images.jianshu.io/upload_images/2898615-2c0f56ad6a5e28d1.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

```
debugComponent=onecomponent,com.huruwo:oneoneponent:1.0.0
```
![QQ截图20171110100700.png](http://upload-images.jianshu.io/upload_images/2898615-04fe16cf902aa093.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by HuRuWo** [comment]
build-gradle 看到了这里:
```
if (str.contains(":")) {
                File file = project.file("../componentrelease/" + str.split(":")[1] + "-release.aar")
                if (file.exists()) {
                    project.dependencies.add("compile", str + "-release@aar")
                    System.out.println("add dependencies : " + str + "-release@aar");
                } else {
                    throw new RuntimeException(str + " not found ! maybe you should generate a new one ")
                }
            } else {
                project.dependencies.add("compile", project.project(':' + str))
                System.out.println("add dependencies project : " + str);
            }
```
是不是只要包含: 就会去 componentrelease 寻找 ，否则 使用 compile 引入

那这种    com.huruwo:oneoneponent:1.0.0 的 aar  应该怎样引入

**Comment by leobert-lan** [comment]
@HuRuWo 去源码找原因非常赞👍

----

debugComponent=onecomponent,com.huruwo:oneoneponent:1.0.0 此处的声明是指要引入的组件，onecomponent这个会以该Module直接编译，com.huruwo:oneoneponent:1.0.0这个是指直接使用一个编译好的aar包，后者算是一个福利，对于稳定的模块，可以直接使用编译好的aar包减少编译工作量提升编译速度。

如果是引用仓库上的内容，在gradle中声明依赖就行了。

**Comment by HuRuWo** [comment]
com.huruwo:oneoneponent:1.0.0 引入失败了 无法找到这个aar 
但是仓库中已有

**Comment by leobert-lan** [comment]
在gradle.properties中声明Component，以这种形式com.huruwo:oneoneponent申明是指到当前的工作空间中的componentrelease目录下找aar，另外其文件命名规则你从代码也能看出来了，应该是：“oneoneponent-release.aar”

**Comment by HuRuWo** [comment]
oneoneponent-release.aar 这样的命名不能 表示版本代号 
我想请教的是:

我已经发布到远程仓库，
如果在`build.gradle` 里面 引用 我可以直接使用`compile "com.huruwo:oneoneponent:1.0.0"`

但是我想利用`gradle.propertie`配置 配合`com.dd.comgradle` 实现加载

请问 `debugComponent=` 这个应该填什么 
已知`com.huruwo:oneoneponent:1.0.0` 失败

**Comment by leobert-lan** [comment]
这里并不能直接这样填，你可以试一下再定义一个前缀表示是远端仓库的，然后改一下plugin。

**Comment by HuRuWo** [comment]
感谢您的回答，我之前已经意识到这个问题。所以对build-gradle 做了修改，成功解决问题。

![image.png](http://upload-images.jianshu.io/upload_images/2898615-db3319f0991d4c88.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

app 中
```
isRunAlone=true
debugComponent=onecomponent,com.huruwo:oneoneponent:1.0.0
```再次感谢
