### ISSUE TITLE
插件重新上传到本地仓库运行报错

### ISSUE THREAD

**Issue by hfbi360** [luojilab/DDComponentForAndroid#43]
Error:Execution failed for task ':app:transformClassesWithComponentCodeForDebug'.
> No such property: Format for class: com.dd.buildgradle.ComCodeTransform
请问这个是什么原因？demo运行没有问题，删除repo后，重新上传到本地仓库运行出现的错误。

**Comment by hfbi360** [comment]
插件工程没有任何修改，其他工程修改了包名

**Comment by HuRuWo** [comment]
应该是delete 问题 我也遇到过

**Comment by mqzhangw** [comment]
这个很可能就是配置或者包名设置问题，在检查一下吧，或者直接使用最新的jcenter上的release包吧
