### ISSUE TITLE
androidTest问题

### ISSUE THREAD

**Issue by pijie** [luojilab/DDComponentForAndroid#45]
J:\DDComponentForAndroid-master\readercomponent\src\androidTest\java\com\mrzhang\comp_reader\ExampleInstrumentedTest.java
Error:(4, 28) 错误: 程序包android.support.test不存在
Error:(5, 35) 错误: 程序包android.support.test.runner不存在
Error:(7, 17) 错误: 程序包org.junit不存在
Error:(8, 24) 错误: 程序包org.junit.runner不存在
Error:(10, 24) 错误: 程序包org.junit不存在
Error:(17, 2) 错误: 找不到符号
符号: 类 RunWith
Error:(19, 6) 错误: 找不到符号
符号:   类 Test
位置: 类 ExampleInstrumentedTest
Error:(22, 30) 错误: 找不到符号
符号:   变量 InstrumentationRegistry
位置: 类 ExampleInstrumentedTest
Error:(24, 9) 错误: 找不到符号
符号:   方法 assertEquals(String,String)
位置: 类 ExampleInstrumentedTest

如果进行单元测试  是不是每个component里面还要添加测试的依赖包呀？

**Comment by leobert-lan** [comment]
Module编写单元测试代码自然是需要添加测试框架依赖的，使用testCompile或者testImplementation（gradle plugin version >= 3.0）。建议在项目空间中定义统一的版本管理。
