### ISSUE TITLE
老是出现 java.io.IOException: Could not delete path 

### ISSUE THREAD

**Issue by HuRuWo** [luojilab/DDComponentForAndroid#46]
使用该组件化方式后 稍微改动项目 就会出现 java.io.IOException: Could not delete path 请问如何解决

**Comment by HuRuWo** [comment]
可是 clean 失败 失败原因 Could not delete

**Comment by mqzhangw** [comment]
如果频繁出现，可以暂时换成反射注册的方式，既调用Router.registerComponent(方法，demo中reader注册share就是这么做的。

**Comment by weinierfei** [comment]
clean如果失败的话,就直接再sync一次,然后重新run就可以了

**Comment by dapengko1** [comment]
我这儿也是这种问题，经常clean和sync，真折磨人，不用组件化就没问题了，请看怎么解决下了

**Comment by leobert-lan** [comment]
这个问题嗯，从另一个角度来看：
组件化的**一个重要目的**就是：使得相对单一的模块能够较简单的进行集成测试（或者说健全性测试更准确一点），只有这个组件被完整通过了，才可以被集成到整个项目中。**所以一边修改某个组件Module，一边编译整个工程，而且是比较频繁的，这种做法本身就不太合适**。

不可否认这也是一个缺陷，等这阵忙完看看能不能修复这个问题。

**Comment by mqzhangw** [comment]
暂时使用反射注册的方式吧，as缓存的问题后续会解决

**Comment by Panjianan** [comment]
我也是经常有这问题,不管是app还是组件都会,就算用isRegisterCompoAuto = false也是一样,用的是as3.0
