### ISSUE TITLE
关于StartActivityForResult

### ISSUE THREAD

**Issue by changshuai7** [luojilab/DDComponentForAndroid#47]
您好，你的组件化方案我从头看了一遍。有个小问题，如果启动一个组件的某个UI页面，能否用StartActivityForResult的方式，想要获取页面回调该如何操作呢？

**Comment by weinierfei** [comment]
你可能要去了解下页面路由,看看阿里开源的arouter吧

**Comment by mqzhangw** [comment]
在UI跳转中是可以通过bundle传递参数的，因此简单的做法是添加一个参数标记需要使用StartActivityForResult的方式来启动，而requestCode也可以通过参数来传递。
