### ISSUE TITLE
定制化的问题

### ISSUE THREAD

**Issue by qiaop** [luojilab/DDComponentForAndroid#49]
在定制化的时候替换成maven仓库的地址这里
`File file = project.file("../componentrelease/" + str.split(":")[1] + "-release.aar")`
是直接将"../componentrelease/"改为maven地址吗？
多谢！

**Comment by mqzhangw** [comment]
不是，这里是使用的引用file的方式，用maven库的话使用compile就好了。不过实际情况要麻烦一些，组件发布到maven是建立在library都发布到maven的基础上的，很多情况下业务library还不够完善，频繁的发布maven比较繁琐，所以需要等到项目已经稳定到一定程度后再做这件事。在项目初期或者人手比较紧张的情况下，建议使用直接依赖本地工程（第一种语法）的方式，更加有灵活性。

**Comment by qiaop** [comment]
啊哦，多谢，这里的File的方式意思就是打包一个aar文件放在compoonentrelease目录下面，然后引用组件的时候直接引用这个目录下的aar。
那么如果我已经发布了正式的aar包到远程maven仓库，那么`private void compileComponents(AssembleTask assembleTask, Project project)`这个方法里的内容是不是就需要做修改？他会不会还是调用的本地的aar文件？多谢！
