### ISSUE TITLE
与我的设计可以相互借鉴

### ISSUE THREAD

**Issue by EndSmile** [luojilab/DDComponentForAndroid#5]
# EoaSplit

我在前段时间为我们的项目设计的模块化方案是：

[EoaSplit](https://github.com/EndSmile/EoaSplit)

现在已经应用到实际的项目开发中，看过这个库之后有很多收获，但是`EoaSplit`与`DDComponentForAndroid`的设计有一些区别，可以供参考：
## 独立的业务接口层
每个业务模块`xx`拥有自己的接口层`xx-common`，接口层放置的是：
 
1. 模块提供给外界调用的接口/接口仓库
2. 模块发出的事件`Event`
3. 模块提供给外界使用的`dto`信息

各个业务模块的接口层一直存在，可以被任意引用

## 业务模块初始化
不是通过指定类名的反射，而是每个业务模块在自己的`AndroidManifest.xml`文件中将初始化类信息通过`meta-data`节点注册，这样在编译的时候每个模块的`meta-data`都会被合并，然后`application`初始化的时候会读取`android:value="module_init"`的节点，并根据`android:name`信息反射读取，这样的好处是如果类被建立了关联，编译器会处理为引用，不会有警告未被调用且重构时不会出现错误，且依赖/解除依赖代码不会报错

```
<meta-data
    android:name="com.ldy.account.receiver.AccountInitReceiver"
    android:value="module_init"/>
```

## 模块间通信
不只是`service`(`facad`)的直接调用形式，还提供了`Event`

1. `NotificationEvent`纯粹的通知事件
2. `GetDatasEvent`需要其它模块提供数据时，而数据的提供方又不确定，发出此事件由其它模块调用此事件的`add`接口添加数据

且事件提供了`plug`，用于记录，拦截事件等

> Activity的跳转使用接口直接调用实现

## 模块配置
模块需要的配置信息，每个模块都需要各种各样的配置信息，这些配置信息可能是`java`中的常量，`resource`资源，`.property`文件等，且配置信息可能多个模块共用，参考`spring`的配置形式

```
account.baseUrl=https://11.12.109.125:8124/eoa-war/api/v2/
```

```
public static final String BASE_URL =
        getStrValue(new PropertyValue("account.baseUrl"), new PropertyValue("baseUrl"));
```
## 业务模块间依赖
模块间依赖是必然存在的，但是不允许平行依赖（业务模块依赖业务模块），业务模块只能依赖别的业务模块的接口层，使用`service`(`facad`)时需要从仓库中取出同时判空（空为业务模块不存在）

`app`作为整个系统的容器，放置配置信息及依赖需要

## 没有的部分

1. 没有对组件的单独调试，这点确实值得借鉴
2. 对非业务组件（view组件，通用功能组件）的特别处理，只是规定了其版本号
3. 没有对界面跳转做特别处理，不过拥有可选的跳转的拦截器
4. 没有对业务模块的卸载做特殊处理（实际需求）

**Comment by EndSmile** [comment]
对了，我超级喜欢罗辑思维，每期视频都看，得到重度用户（有6个付费订阅。。），求内推，我个人对
1. 代码架构设计
2. kotlin
3. 自定义控件

喜欢且有特别的理解和追求，热爱阅读，学习，挑战更高的难度

可以私聊：745472638@qq.com

**Comment by mqzhangw** [comment]
非常高兴能把你的方案也分享出来，我大致看了一下，在组件注册等方面的确启发很大，太感谢了。
我感觉两个方案之前的区别除了你说的单独调试之外，还有两点是“得到”方案的创新之处：一是组件单独调试和集成调试的无缝切换，这个你运行一下demo就可以体会到这个便利之处；二是做到了组件之间的代码边界，目前可以做到组件之间完全杜绝越过接口直接调用实现类的错误，也只有做到这中完全隔离才能够做到动态的加载和卸载组件。

**Comment by EndSmile** [comment]
嗯，大家的思路还是比较一致的，只不过当时我是把每个模块暴露的接口单独建立了`module`，"得到"的设计是将这些接口统一放置在`componentservice`模块中，我们组件的实现层都是不能直接相互依赖，因此组件之间的代码边界都是没有问题的。

组件单独调试和集成调试的无缝切换确实非常棒，非常方便，值得借鉴

**Comment by mqzhangw** [comment]
赞，共同进步👍
