### ISSUE TITLE
组件间的多播处理

### ISSUE THREAD

**Issue by YummyLau** [luojilab/DDComponentForAndroid#50]
感谢作者的开源资料及文章，收益匪浅。
有个问题几个问题想请教下：
1. 如果组件A引用引用组件B的某个类，该类是否需要下沉到service层；
2. 如果业务中涉及到1场景，如果多个组件引用组件B的某个类，当该类的某些变量改变时需要广播，如何如理。（目前我的做法是eventbus，同时下沉该类到service解决各组件间的编译依赖问题）；
3. 一般登录类账号管理，是否会视为组件级别，还是在service层之上，普通组件之下。

谢谢！

**Comment by mqzhangw** [comment]
1、组件之间是禁止类引用的（实际上也做不到）。在这种情况下就需要B通过接口的形式提供这个类的功能，A通过接口来调用。有一个特殊情况就是这个类如果是model等纯数据类，可以作为提供的服务的一部分下沉到service
2、eventbus是个不错的解决方案，这种情况下需要把event事件定义在service中。当然是用回调的方式，自己实现一个多播也是可以的。
3、登录模块是需要当做一个组件的，与其他组件平级即可。组件之间是可以相互引用的，引用的方式也是在gradle.properties配置
