### ISSUE TITLE
share中如果用到application的context怎么处理？

### ISSUE THREAD

**Issue by dayday0769** [luojilab/DDComponentForAndroid#51]
如题，现在如果直接运行app，当调用用share项目时会报空指针（找不到share的application）

**Comment by weinierfei** [comment]
可以参考 [issue 30](https://github.com/luojilab/DDComponentForAndroid/issues/30) 和 [issue 33](https://github.com/luojilab/DDComponentForAndroid/issues/33)

**Comment by dayday0769** [comment]
好的，谢谢
