### ISSUE TITLE
想问下混淆怎么处理

### ISSUE THREAD

**Issue by dayday0769** [luojilab/DDComponentForAndroid#52]
如题，我引用的libs都在basiclib module,那么是每个module都针对用到的libs做混淆处理，还是只在app做混淆处理或者在basiclib做混淆处理？
现在打release包的时候由于有混淆，遇到了这样一个错误：Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> Unexpected scopes found in folder '/.../app/build/intermediates/transforms/proguard/release'. Required: EXTERNAL_LIBRARIES, PROJECT, SUB_PROJECTS. Found: LOCAL_DEPS, PROJECT

**Comment by mqzhangw** [comment]
只在app里面进行混淆处理就好了。
你这个问题应该和组件化没有关系，你google一下解决方式吧
