### ISSUE TITLE
切换组件运行，会出现ClassNotFoundException，clean之后再运行就ok

### ISSUE THREAD

**Issue by gaoneng102** [luojilab/DDComponentForAndroid#56]
java.lang.RuntimeException: Unable to instantiate application com.mrzhang.share.runalone.application.ShareApplication: java.lang.ClassNotFoundException: Didn't find class "com.mrzhang.share.runalone.application.ShareApplication" on path: DexPathList[[zip file "/data/app/com.mrzhang.share-1/base.apk"],nativeLibraryDirectories=[/data/app/com.mrzhang.share-1/lib/arm, /vendor/lib, /system/lib]]

**Comment by mqzhangw** [comment]
切换组件，你的意思是之前单独运行reader，切换成单独运行reader吗？

**Comment by gaoneng102** [comment]
@mqzhangw 之前组件reader单独运行，然后切换到share组件单独运行，就出现上面的问题

**Comment by mqzhangw** [comment]
嗯，这估计有概率出问题，因为as会缓存上次运行的数据，这个我看后面怎么在切换后强制clean。目前使用时，先手动clean一下在运行吧

**Comment by lilipu1** [comment]
我也是出现了这个问题,百分之百出现

**Comment by mqzhangw** [comment]
切换组件后记得clean
