### ISSUE TITLE
请教一下三个注册组件的区别

### ISSUE THREAD

**Issue by flyingshare** [luojilab/DDComponentForAndroid#59]
Router.registerComponent();
router.addService();
uiRouter.registerUI();

这三种分别是什么作用

另外项目中
ReadBookService service = (ReadBookService)router.getService(ReadBookService.class.getSimpleName());
service始终是null，会是什么原因呢？

**Comment by mqzhangw** [comment]
你如果仔细看一下对应的两篇文章就能理解了。
第一个是注册组件，需要传入组件的ApplicationLike的全限定名
第二个是注册组件提供的服务，用于组件间数据交互
第三个是注册UI跳转服务
如果你拿到的service一直是null，肯定是第一步和第二步除了问题。
