### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by pozhupt** [luojilab/DDComponentForAndroid#60]
我打算把这个项目试用到我们新开发的项目中，还是发现各种各种的问题，比如，组件怎么跳到主app模块的activity中？比如当我组件测试完成后，将isAlone=false,然后运行assmeRealese，发现报一个找到模块的问题，比如某些本来没问题的模块资源会突然报无法转换成英文的问题，希望提高稳定性吧，感觉暂时不太适合用于正式项目。

**Comment by mqzhangw** [comment]
跳转到主项目很简单，app也提供服务和UI跳转就可以了啊。
至于其他问题，贴一下具体报错日志吧，这个组件化方案已经在得到app上运行半年多了，没有出现问题。
