### ISSUE TITLE
多个组件引用同一个库问题

### ISSUE THREAD

**Issue by nevergoneok** [luojilab/DDComponentForAndroid#61]
两个组件引用同一个库，在baselib里面加入此库的引用，但是同步后组件依然找不到库，只有在两个组件都单独引用库时才找的到，这样操作后，切换到主module app，run一直报错
Error:Execution failed for task ':basiclib:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug'.
> java.lang.RuntimeException: java.io.IOException: Failed to delete D:\***\basiclib\build\intermediates\intermediate-jars\debug\classes.jar

**Comment by mqzhangw** [comment]
baselib引用的库在所有组件都是可以看到的啊，你用的是compile还是implementation？

**Comment by nevergoneok** [comment]
即使gradle3.0.0的问题修复了，依然会上上述的错误，一直同步成功，run就报错

**Comment by mqzhangw** [comment]
run之前先clean一次呢

**Comment by nevergoneok** [comment]
我打开其他项目也会出这样的问题了，run之前clean不行的，还是会报Could not delete，主动删除又会报IOException，是否是AS3.0的bug？

**Comment by leobert-lan** [comment]
是不是编译使用了：parallel？好像这个会产生一些“美妙”的问题。也有可能是传递性依赖的问题。用Gradle的dependencyInsight功能查一下依赖树看看。

**Comment by mqzhangw** [comment]
如果其他项目有问题，估计和组件化无关了

**Comment by zengjingfang** [comment]
同样遇到这个问题，后面有解决办法吗？
![image](https://user-images.githubusercontent.com/11888369/39294705-f78d5a1a-496e-11e8-9b73-f799b5a132ae.png)
