### ISSUE TITLE
远程库插件配置

### ISSUE THREAD

**Issue by yuanjunli** [luojilab/DDComponentForAndroid#63]
文档中写的以下配置无法获取到插件：
`classpath 'com.luojilab.andcomponent:build-gradle:1.0.0'`
查看demo中的配置是:
`classpath 'com.luojilab.ddcomponent:build-gradle:1.0.0'`

是否文档上写错了

**Comment by mqzhangw** [comment]
sorry,的确写错了，发到jcenter的时候改过一次包名。
谢谢指出错误👍
