### ISSUE TITLE
could not be found in project

### ISSUE THREAD

**Issue by Yanqilong** [luojilab/DDComponentForAndroid#66]

**Comment by Yanqilong** [comment]
组件启动的时候报错，是什么原因？
Error:(1, 1) A problem occurred evaluating project ':welcome'.
> Failed to apply plugin [id 'com.dd.comgradle']
   > Project with path ':''' could not be found in project ':welcome'.

**Comment by mqzhangw** [comment]
gradle.properties配置有误，配置发一下吧

**Comment by Yanqilong** [comment]
不好意思，忘记提问了这个问题

首先是子模块welcome的build.gradle
dependencies {
    implementation project(':componentservice')
}
combuild {
    applicationName = 'com.newseax.welcome.application.WelcomeApplication'
    isRegisterCompoAuto = true
}

gradle.properties
isRunAlone=true

然后是主模块的build.gradle
combuild {
    applicationName = 'com.newseax.application.NewSeaXApplication'
    isRegisterCompoAuto = true
}

gradle.properties
isRunAlone=true
debugComponent='com.newseax.welcome:welcome'
compileComponent='welcome'

顶级gradle.properties
mainmodulename=app

**Comment by Yanqilong** [comment]
gradle.properties
isRunAlone=false

现在打arr的时候会报这错

Error:(1, 1) A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.dd.comgradle']
   > Project with path ':'welcome'' could not be found in project ':app'.

**Comment by Yanqilong** [comment]
找到了问题，依赖引用的属性加了单引号，掌脸～～，问题关闭了
