### ISSUE TITLE
期待后期对Instant Run很好的支持

### ISSUE THREAD

**Issue by yuanshenbin** [luojilab/DDComponentForAndroid#7]
学习了一下，很不错，希望后期能优化支持 Instant Run，我们公司的项目，组件化已经一段时间了，确实没考虑很好的解耦，后面也会改成，面向接口的方式

**Comment by mqzhangw** [comment]
使用反射注册的化是支持Instant Run的，自动字节码插入有时不支持Instant Run的问题暂时找不到解决思路，你可以暂时先第一种方式
