### ISSUE TITLE
请问如何解决子组件中打包AAR后，主module找不到子组件远程依赖的类

### ISSUE THREAD

**Issue by keep2iron** [luojilab/DDComponentForAndroid#70]
因为在使用得到团队的这个组件化方案之后，发现子模块的依赖，主模块无法找到，请问有什么好的解决办法

**Comment by leobert-lan** [comment]
如果说有多个module都需要使用到某个类库，可以在baselib中声明依赖。

**Comment by keep2iron** [comment]
哇。大佬回复真快！在这里谢谢了。不过能否对于组件插件集成maven呢，这样做成一个本地依赖

**Comment by keep2iron** [comment]
http://blog.csdn.net/zsf442553199/article/details/77882531

**Comment by keep2iron** [comment]
谢谢，您的意见，经过查找资料发现 http://blog.csdn.net/zsf442553199/article/details/77882531，这篇是针对aar打包无法找到的远程依赖的一个方案，希望组件化能够下一个版本能支持一下，弄成这种，支持子module依赖的一个方案。谢谢了

**Comment by leobert-lan** [comment]
如果有feature建议的话可以单独提一个issue。这套方案最大的价值在于代码解耦，模块解耦和简化开发人员自己做模块的集成测试。另外CSDN那个网址404

**Comment by keep2iron** [comment]
好的，谢谢了，我先目前先把依赖放到base库里面。csdn我这里能打开^_^。能否有群或者讨论组一起讨论一下呢，我也觉得这套方案相当不错
