### ISSUE TITLE
编译时代码检测问题

### ISSUE THREAD

**Issue by Jusenr** [luojilab/DDComponentForAndroid#72]
编译时，会有代码检测，有时编译不过  

建议，在相关的build.gradle 添加

 lintOptions {
        checkReleaseBuilds false
        // Or, if you prefer, you can continue to check for errors in release builds,
        // but continue the build even when errors are found:
        abortOnError false
    }

**Comment by mqzhangw** [comment]
这个使用的时候自己定义吧，有些app可能依赖lint
