### ISSUE TITLE
gradle assembleRelease出错，proguard混淆有问题

### ISSUE THREAD

**Issue by ihrthk** [luojilab/DDComponentForAndroid#8]
<img width="964" alt="screen shot 2017-09-12 at 15 07 09" src="https://user-images.githubusercontent.com/2418260/30312440-1d298d02-97cc-11e7-8dc4-681c8f68bff4.png">

**Comment by mqzhangw** [comment]
https://github.com/mqzhangw/AndroidComponent/issues/4
之前有人反馈这个问题，方案与proguard没有关系，应该是proguard配置的问题。你可以参考这个检查一下
