### ISSUE TITLE
onActivityResult 是不是不支持   @Autowired

### ISSUE THREAD

**Issue by Rethen** [luojilab/DDComponentForAndroid#80]
如题

**Comment by mqzhangw** [comment]
你是说onActivityResult中传入的参数吧，这个不支持，也没有太大必要吧

**Comment by Rethen** [comment]
实际上我就想只用注解，不用有些写注解，有些是intent.getString 这种方式

**Comment by mqzhangw** [comment]
现在的注解机制只是为组件化UI跳转定制的，功能不够强大，如果只用注解，建议找更专业的注解方案吧
