### ISSUE TITLE
关于application初始化及Context上下文

### ISSUE THREAD

**Issue by SunnyLy** [luojilab/DDComponentForAndroid#81]
hi,
我想请教下，
1，如果我有些基础参数初始化是放在apllication onCreate里面的，比如网络框架，数据库等，现在组件化后，这些操作怎么放呢？

2，组件如何获取application的 context呢？

**Comment by mqzhangw** [comment]
1、组件中有一个ApplicationLike类，作用就类似于Application
2、demo中有个BaseApplication，你可以看一下
