### ISSUE TITLE
建议添加功能：对不同 productFlavor 配置不同的组件集合

### ISSUE THREAD

**Issue by yue001** [luojilab/DDComponentForAndroid#83]
可考虑把 host app 的 gradle.properties 放在 productFlavor 相应目录中；

**Comment by mqzhangw** [comment]
demo中没涉及区分不同flavor，你可以自己试一下

**Comment by yue001** [comment]
试了，但我在插件中没有找到获取flavor的方法，不知您有没有一些建议或思路，这个功能还是很有必要的。

**Comment by mqzhangw** [comment]
获取flavor也是可以做到的，也是分析task的名称，一般都是assembleFlavorRelease的形式
