### ISSUE TITLE
返回页面传值问题

### ISSUE THREAD

**Issue by yubaokang** [luojilab/DDComponentForAndroid#84]
A页面列表，
B页面详情页，
B页面进行某项操作之后，需要刷新A页面item的数据，
这种情况可以处理吗？

**Comment by mqzhangw** [comment]
这种就用eventbus吧，和组件化没关系。如果是跨组件，可以通过服务或者共享event的方式

**Comment by yubaokang** [comment]
@mqzhangw eventbus还是没有完全解耦

**Comment by mqzhangw** [comment]
那就用服务接口来刷新数据，一般也只有这两种方式
