### ISSUE TITLE
想更早的使用到Router.getInstance().getService()方法.

### ISSUE THREAD

**Issue by qingyongai** [luojilab/DDComponentForAndroid#85]
场景:
我写了一个组件比如用户模块，用户模块里面有一些init的代码必须在Application的onCreate里面调用
问题:
现在的gradle插件处理问题是自动把代码加在onCreate的最后的，显然不行的，模块都没有初始化。

现在我这边的解决方案是，规定好一个方法，initApplike，然后在gradle插件处理代码的时候检测用户是使用者是否有定义这样一个方法，如果有的话，就在这个方法里面生成模块注册的代码，这个方法由开发者自己调用。
不知道是否有更好的解决方案，如果觉得这个方法和这个需求是合理的我就提个pr。当然有更好的解决方案更好。

**Comment by mqzhangw** [comment]
如果想更精细的控制初始化顺序，可以使用反射注册组件的方式，这样就可以添加在任意的地方

**Comment by qingyongai** [comment]
这个我知道，但是还是希望自动的
