### ISSUE TITLE
我只要一改代码，再运行就会报这个错

### ISSUE THREAD

**Issue by JavaNoober** [luojilab/DDComponentForAndroid#86]
Error:Execution failed for task ':app:transformClassesWithDesugarForDebug'.
> com.android.build.api.transform.TransformException: java.io.IOException: Could not delete path 'E:\android-project\palegreen\app\build\intermediates\transforms\desugar\debug\0.jar'.

这个是为什么呢，太影响敲代码效率了，每次一定要clean才能再运行

**Comment by mqzhangw** [comment]
检查一下as，或者采用反射的方式来注册路由

**Comment by xinboljy** [comment]
我也遇到过这问题，请问下大佬请问检查以下as是什么意思呢？
