### ISSUE TITLE
组件可否支持java文件与kotlin文件混编？

### ISSUE THREAD

**Issue by GreenPepperForPotato** [luojilab/DDComponentForAndroid#87]
混编的组件，Applike文件无法在编译的时候插入app里面的application中去。把组件中的kotline文件替换成java文件，就可以正常插入进去。看你demo 里面的 java模块。跟kotlin模块是区分开的。是不是不支持同一模块混编？在线等待。谢谢~

**Comment by mqzhangw** [comment]
如果你组件中有kotlin文件，需要在gradle中配置：
apply plugin: 'kotlin-android'
dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
}
AS也会给出提示的，只要你注意右下角的弹窗就可以看到
