### ISSUE TITLE
com.alibaba.fastjson.JSONException: default constructor not found. class 

### ISSUE THREAD

**Issue by GreenPepperForPotato** [luojilab/DDComponentForAndroid#88]
用kotlin写了一个数据类ShareIMMessage。
![image](https://user-images.githubusercontent.com/13328957/36090193-6524ebbc-101a-11e8-92c7-8cdfc296b893.png)

然而jsonService.parseObject(substitute.getIntent().getStringExtra("message"), ShareIMMessage.class)这句代码抛异常，com.alibaba.fastjson.JSONException: default constructor not found. class  。我看fastjson的github官网上也有提类似的issue。一直没解决，哪位有应对之策？

**Comment by mqzhangw** [comment]
换成最新的fastjson版本仍然有问题，已经换成使用Gson，新发布componentlib 1.3.0版本，你可以更新一下
