### ISSUE TITLE
外链打开问题

### ISSUE THREAD

**Issue by leobert-lan** [luojilab/DDComponentForAndroid#90]
当前的UI路由设计中，每个Module都设计了独立的host，导致通过外链打开时，需要进行以下方案处理：

- 每个Module都具有处理分发的Activity，且uri类似：ddcompo://share/shareBook...此类格式，host受到客户端较强的限制

- url处理成回调类型，由统一的分发Activity响应处理，真正的跳转url封装在参数内，例如：ddcompo://www.luojilab.com/compodemo?target=share/shareBook?bookName=....

**Comment by mqzhangw** [comment]
外链的响应由scheme来触发，可以在manifest中配置一个入口的Activity，然后这个Activity将URI转发给UIRouter，类似于一个简单的分发功能就可以了
