### ISSUE TITLE
我想问下，怎样实现类似广播的功能？

### ISSUE THREAD

**Issue by m5314** [luojilab/DDComponentForAndroid#91]
直接用brocast或eventbus吗？

**Comment by leobert-lan** [comment]
首先，选用broadcastReceiver或是EventBus看你的需求；
这两者可能困惑你的是：类被隔离。

对于BroadcastReceiver，我建议将类定义在会发出该广播的Module内，并在相应的ComponentService中定义注册、反注册广播接收器的方法，定义Callback接口由“消费者”Module实现具体的消费逻辑。按照IOC来处理，而不要将BroadCastReceiver定义在“公共区”

对于EventBus，他的Event既是事件也是数据，建议定义在公共区（ComponentService中）

-----
By the way：

ComponentService 的本职是对外提供本模块内的、封装过的业务，所以牵涉到的入口数据类、出口数据类、回调接口等都应当在此定义。
