### ISSUE TITLE
gson 与项目本地的gson 冲突

### ISSUE THREAD

**Issue by gexiangjie** [luojilab/DDComponentForAndroid#93]
因为我们的项目为了处理数据为null的情况把gson 弄成本地的了,所以在使用插件的过程中
![image](https://user-images.githubusercontent.com/9777969/36773771-388b8e16-1c96-11e8-9638-abc6948730b5.png) 会与我们项目中的重复

**Comment by mqzhangw** [comment]
这样的话你可以把源码中JsonServiceImpl的实现改成自己本地的gson，然后发布到公司的maven。后面我想办法把序列化这块暴露出来
