### ISSUE TITLE
运行demo后log日志

### ISSUE THREAD

**Issue by TomorrowDreamer** [luojilab/DDComponentForAndroid#94]
03-01 14:44:43.716 31139-31139/com.luojilab.androidcomponent W/System: ClassLoader referenced unknown path: /data/app/com.luojilab.androidcomponent-1/lib/arm64
03-01 14:44:43.761 31139-31139/com.luojilab.androidcomponent W/System.err: java.lang.ClassNotFoundException: com.luojilab.gen.router.ReaderUiRouter
03-01 14:44:43.764 31139-31139/com.luojilab.androidcomponent W/System.err:     at java.lang.Class.classForName(Native Method)
03-01 14:44:43.764 31139-31139/com.luojilab.androidcomponent W/System.err:     at java.lang.Class.forName(Class.java:324)
03-01 14:44:43.764 31139-31139/com.luojilab.androidcomponent W/System.err:     at java.lang.Class.forName(Class.java:285)
03-01 14:44:43.764 31139-31139/com.luojilab.androidcomponent W/System.err:     at com.luojilab.component.componentlib.router.ui.UIRouter.fetch(UIRouter.java:175)
03-01 14:44:43.764 31139-31139/com.luojilab.androidcomponent W/System.err:     at com.luojilab.component.componentlib.router.ui.UIRouter.registerUI(UIRouter.java:72)
03-01 14:44:43.764 31139-31139/com.luojilab.androidcomponent W/System.err:     at com.luojilab.reader.applike.ReaderAppLike.onCreate(ReaderAppLike.java:20)
03-01 14:44:43.764 31139-31139/com.luojilab.androidcomponent W/System.err:     at com.luojilab.component.componentlib.router.Router.registerComponent(Router.java:73)
03-01 14:44:43.764 31139-31139/com.luojilab.androidcomponent W/System.err:     at com.luojilab.componentdemo.application.AppApplication.onCreate(AppApplication.java:20)
03-01 14:44:43.764 31139-31139/com.luojilab.androidcomponent W/System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1015)
03-01 14:44:43.764 31139-31139/com.luojilab.androidcomponent W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4793)
03-01 14:44:43.764 31139-31139/com.luojilab.androidcomponent W/System.err:     at android.app.ActivityThread.access$1600(ActivityThread.java:165)
03-01 14:44:43.764 31139-31139/com.luojilab.androidcomponent W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1437)
03-01 14:44:43.764 31139-31139/com.luojilab.androidcomponent W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
03-01 14:44:43.764 31139-31139/com.luojilab.androidcomponent W/System.err:     at android.os.Looper.loop(Looper.java:150)
03-01 14:44:43.764 31139-31139/com.luojilab.androidcomponent W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5621)
03-01 14:44:43.764 31139-31139/com.luojilab.androidcomponent W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
03-01 14:44:43.764 31139-31139/com.luojilab.androidcomponent W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
03-01 14:44:43.764 31139-31139/com.luojilab.androidcomponent W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
03-01 14:44:43.764 31139-31139/com.luojilab.androidcomponent W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.luojilab.gen.router.ReaderUiRouter" on path: DexPathList[[zip file "/data/app/com.luojilab.androidcomponent-1/base.apk"],nativeLibraryDirectories=[/data/app/com.luojilab.androidcomponent-1/lib/arm64, /vendor/lib64, /system/lib64]]
03-01 14:44:43.768 31139-31139/com.luojilab.androidcomponent W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
03-01 14:44:43.768 31139-31139/com.luojilab.androidcomponent W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
03-01 14:44:43.768 31139-31139/com.luojilab.androidcomponent W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
03-01 14:44:43.768 31139-31139/com.luojilab.androidcomponent W/System.err: 	... 18 more
03-01 14:44:43.768 31139-31139/com.luojilab.androidcomponent W/System.err: 	Suppressed: java.lang.ClassNotFoundException: com.luojilab.gen.router.ReaderUiRouter
03-01 14:44:43.773 31139-31139/com.luojilab.androidcomponent W/System.err:     at java.lang.Class.classForName(Native Method)
03-01 14:44:43.773 31139-31139/com.luojilab.androidcomponent W/System.err:     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
03-01 14:44:43.773 31139-31139/com.luojilab.androidcomponent W/System.err:     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
03-01 14:44:43.773 31139-31139/com.luojilab.androidcomponent W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
03-01 14:44:43.773 31139-31139/com.luojilab.androidcomponent W/System.err: 		... 19 more
03-01 14:44:43.773 31139-31139/com.luojilab.androidcomponent W/System.err: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
03-01 14:44:43.777 31139-31139/com.luojilab.androidcomponent W/System.err: java.lang.ClassNotFoundException: com.luojilab.gen.router.ReaderUiRouter
03-01 14:44:43.778 31139-31139/com.luojilab.androidcomponent W/System.err:     at java.lang.Class.classForName(Native Method)
03-01 14:44:43.778 31139-31139/com.luojilab.androidcomponent W/System.err:     at java.lang.Class.forName(Class.java:324)
03-01 14:44:43.778 31139-31139/com.luojilab.androidcomponent W/System.err:     at java.lang.Class.forName(Class.java:285)
03-01 14:44:43.778 31139-31139/com.luojilab.androidcomponent W/System.err:     at com.luojilab.component.componentlib.router.ui.UIRouter.fetch(UIRouter.java:175)
03-01 14:44:43.778 31139-31139/com.luojilab.androidcomponent W/System.err:     at com.luojilab.component.componentlib.router.ui.UIRouter.registerUI(UIRouter.java:72)
03-01 14:44:43.778 31139-31139/com.luojilab.androidcomponent W/System.err:     at com.luojilab.reader.applike.ReaderAppLike.onCreate(ReaderAppLike.java:20)
03-01 14:44:43.778 31139-31139/com.luojilab.androidcomponent W/System.err:     at com.luojilab.componentdemo.application.AppApplication.onCreate(AppApplication.java:22)
03-01 14:44:43.778 31139-31139/com.luojilab.androidcomponent W/System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1015)
03-01 14:44:43.778 31139-31139/com.luojilab.androidcomponent W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4793)
03-01 14:44:43.778 31139-31139/com.luojilab.androidcomponent W/System.err:     at android.app.ActivityThread.access$1600(ActivityThread.java:165)
03-01 14:44:43.778 31139-31139/com.luojilab.androidcomponent W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1437)
03-01 14:44:43.778 31139-31139/com.luojilab.androidcomponent W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
03-01 14:44:43.778 31139-31139/com.luojilab.androidcomponent W/System.err:     at android.os.Looper.loop(Looper.java:150)
03-01 14:44:43.778 31139-31139/com.luojilab.androidcomponent W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5621)
03-01 14:44:43.778 31139-31139/com.luojilab.androidcomponent W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
03-01 14:44:43.778 31139-31139/com.luojilab.androidcomponent W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
03-01 14:44:43.778 31139-31139/com.luojilab.androidcomponent W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
03-01 14:44:43.778 31139-31139/com.luojilab.androidcomponent W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.luojilab.gen.router.ReaderUiRouter" on path: DexPathList[[zip file "/data/app/com.luojilab.androidcomponent-1/base.apk"],nativeLibraryDirectories=[/data/app/com.luojilab.androidcomponent-1/lib/arm64, /vendor/lib64, /system/lib64]]
03-01 14:44:43.778 31139-31139/com.luojilab.androidcomponent W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
03-01 14:44:43.778 31139-31139/com.luojilab.androidcomponent W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
03-01 14:44:43.778 31139-31139/com.luojilab.androidcomponent W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
03-01 14:44:43.778 31139-31139/com.luojilab.androidcomponent W/System.err: 	... 17 more
03-01 14:44:43.778 31139-31139/com.luojilab.androidcomponent W/System.err: 	Suppressed: java.lang.ClassNotFoundException: com.luojilab.gen.router.ReaderUiRouter
03-01 14:44:43.779 31139-31139/com.luojilab.androidcomponent W/System.err:     at java.lang.Class.classForName(Native Method)
03-01 14:44:43.779 31139-31139/com.luojilab.androidcomponent W/System.err:     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
03-01 14:44:43.779 31139-31139/com.luojilab.androidcomponent W/System.err:     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
03-01 14:44:43.779 31139-31139/com.luojilab.androidcomponent W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
03-01 14:44:43.779 31139-31139/com.luojilab.androidcomponent W/System.err: 		... 18 more
03-01 14:44:43.779 31139-31139/com.luojilab.androidcomponent W/System.err: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
03-01 14:44:43.831 31139-31139/com.luojilab.androidcomponent I/HwCust: Constructor found for class android.app.HwCustHwWallpaperManagerImpl
com.luojilab.androidcomponent W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
com.luojilab.androidcomponent W/System.err: java.lang.ClassNotFoundException: com.luojilab.componentdemo.MainActivity$$Router$$Autowired
com.luojilab.androidcomponent W/System.err:     at java.lang.Class.classForName(Native Method)
com.luojilab.androidcomponent W/System.err:     at java.lang.Class.forName(Class.java:324)
com.luojilab.androidcomponent W/System.err:     at java.lang.Class.forName(Class.java:285)
com.luojilab.androidcomponent W/System.err:     at com.luojilab.component.componentlib.service.AutowiredServiceImpl.autowire(AutowiredServiceImpl.java:36)
com.luojilab.androidcomponent W/System.err:     at com.luojilab.component.basicres.BaseActivity.onCreate(BaseActivity.java:18)
com.luojilab.androidcomponent W/System.err:     at com.luojilab.componentdemo.MainActivity.onCreate(MainActivity.java:28)
com.luojilab.androidcomponent W/System.err:     at android.app.Activity.performCreate(Activity.java:6367)
com.luojilab.androidcomponent W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
com.luojilab.androidcomponent W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2404)
com.luojilab.androidcomponent W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2511)
com.luojilab.androidcomponent W/System.err:     at android.app.ActivityThread.access$900(ActivityThread.java:165)
com.luojilab.androidcomponent W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1375)
com.luojilab.androidcomponent W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
com.luojilab.androidcomponent W/System.err:     at android.os.Looper.loop(Looper.java:150)
com.luojilab.androidcomponent W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5621)
com.luojilab.androidcomponent W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
com.luojilab.androidcomponent W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
com.luojilab.androidcomponent W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
com.luojilab.androidcomponent W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.luojilab.componentdemo.MainActivity$$Router$$Autowired" on path: DexPathList[[zip file "/data/app/com.luojilab.androidcomponent-1/base.apk"],nativeLibraryDirectories=[/data/app/com.luojilab.androidcomponent-1/lib/arm64, /vendor/lib64, /system/lib64]]
com.luojilab.androidcomponent W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
com.luojilab.androidcomponent W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
com.luojilab.androidcomponent W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
com.luojilab.androidcomponent W/System.err: 	... 18 more
com.luojilab.androidcomponent W/System.err: 	Suppressed: java.lang.ClassNotFoundException: com.luojilab.componentdemo.MainActivity$$Router$$Autowired
com.luojilab.androidcomponent W/System.err:     at java.lang.Class.classForName(Native Method)
com.luojilab.androidcomponent W/System.err:     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
com.luojilab.androidcomponent W/System.err:     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
com.luojilab.androidcomponent W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
com.luojilab.androidcomponent W/System.err: 		... 19 more

**Comment by mqzhangw** [comment]
用Instant Run了吗

**Comment by mqzhangw** [comment]
检查一下类有没有生成，或者混淆配置是否正确吧
