### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "com.luojilab.componentdemo.application.AppApplication" on path: DexPathList

### ISSUE THREAD

**Issue by wangqingnan** [luojilab/DDComponentForAndroid#96]
子组件运行都正常，整合到app以后，一运行就报这个错，怎么clean都没用，求助

**Comment by mqzhangw** [comment]
运行的demo？

**Comment by wangqingnan** [comment]
运行demo是好的，但是我重命名了项目命和readercomponent的model名以及里面的类名，就这样了，不知道是哪一步做错导致这个问题

**Comment by wangqingnan** [comment]
能否给点提示

**Comment by wangqingnan** [comment]
我找到问题所在了，我修改readercomponent的model名以及里面的类名是没有问题的

但是修改项目名的话就会产生这个问题。

我修改项目名的方式是退出Android studio，直接修改文件夹的名字

请问有什么解决方案么，谢谢！

**Comment by mqzhangw** [comment]
你应该用refactor功能吧？如果你修改了包名，那肯定不是com.luojilab.componentdemo.application.AppApplication了，这个换成你改之后的就可以了

**Comment by wangqingnan** [comment]
不是哦，包名还是原来的包名，只是把DDComponentForAndroid-master这个项目名改了
